name: Release Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install

      - name: Build executable with PyInstaller
        run: |
          poetry run dist

      - name: Install NSIS
        run: choco install nsis -y

      - name: Package with NSIS
        run: |
          makensis .nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: paperback-selfdiagnosis-tool-setup
          path: paperback-selfdiagnosis-tool-setup.exe
